--[[

URL: https://giphy.com/gifs/3o7btZzyj3zGh20SSk
Platform: Giphy

--]]
return {
    title = "Bouncing Ray",
    name = "b-ray",
    width = 16,
    height = 16,
    frame_delays = { 0.1 },
    frames = {
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "404040", "292626", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "b4b4b4", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "fefefe", nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "fefefe", nil, "fefefe", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "b3b3b3", nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "b4b4b4", nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "b3b3b3", nil, nil, "fefefe", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "404040", nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "404040", nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "404040", nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "404040", nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "292626", nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "292626", nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "292626", nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "292626", nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "292626", nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "5f5f5f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "b4b4b4", "b4b4b4", nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "808080", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "e0e0e0", "ffffff", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "ffffff", "ffffff", nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "808080", nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "b4b4b4", "e0e0e0", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "808080", "808080", "808080", nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "606060", nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "808080", "b3b3b3", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "404040", "404040", "3f3f3f", "404040", nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "404040", nil, nil, "b5b5b5", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "606060", "7f7f7f", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "292626", "292626", "282525", "292626", "292626", nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "292626", nil, nil, "808080", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "404040", "606060", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, "b4b4b4", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "dfdfdf", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7f7f7f", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "292626", "404040", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, "fefefe", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "e1e1e1", nil, "ffffff", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b3b3b3", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, "808080", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "e0e0e0", nil, "808080", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, "808080", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, "404040", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "020202", "e0e0e0", nil, nil, "404040", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, "404040", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, "404040", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, "292626", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, "292626", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, "292626", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, "292626", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, "292626", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "b4b4b4", "b4b4b4", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "fefefe", "ffffff", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "ffffff", "e0e0e0", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "808080", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, "808080", "808080", "808080", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "e0e0e0", "b4b4b4", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "ffffff", nil, nil, "808080", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "606060", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "404040", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, "292626", "292626", "292626", "292626", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "b4b4b4", "808080", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "e0e0e0", nil, nil, "606060", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, "404040", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "292626", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, "292626", "292626", "292626", "292626", "292626", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "808080", "606060", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "b4b4b4", nil, nil, "404040", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, "292626", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "606060", "404040", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "808080", nil, nil, "292626", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "b4b4b4", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "e0e0e0", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "010101", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
        }
    }
}
