--[[

URL: https://giphy.com/gifs/pixel-xUPGcHCijXhfAFNi80
Platform: Giphy

--]]
return {
    title = "Factory Belt",
    name = "belt",
    width = 16,
    height = 16,
    frame_delays = { 0.1 },
    frames = {
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", "636363", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "585858", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", "636363", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "585858", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", "636363", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "5b5b5b", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", "666666", "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "5a5a5a", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", "646464", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "5a5a5a", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", "646464", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "585858", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "8b8b8b", "4f4f4f", "4f4f4f", "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4f4f4f", nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4f4f4f", nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "7e7e7e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "787878", "646464", "4a4a4a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "585858", "4f4f4f", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "8b8b8b", "4f4f4f", "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "4f4f4f", nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "4f4f4f", nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "7c7c7c", "646464", "4d4d4d", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "5b5b5b", "4f4f4f", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "8b8b8b", "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "4c4c4c", nil, "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "4c4c4c", nil, "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "7c7c7c", "666666", "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "595959", "4c4c4c", "434343", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "7a7a7a", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "7d7d7d", "666666", "4c4c4c", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "585858", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "8b8b8b", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4b4b4b", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "434343", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "636363", "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7d7d7d", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", "636363", "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4b4b4b", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8a8a8a", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8a8a8a", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8a8a8a", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", "656565", "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "5b5b5b", "4e4e4e", "424242", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7d7d7d", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", "636363", "4b4b4b", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "585858", "4e4e4e", "424242", nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4e4e4e", nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4e4e4e", nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4e4e4e", nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", "666666", "4e4e4e", nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "161616", "181818", "171717", "181818", "181818", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7d7d7d", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7c7c7c", "646464", "4b4b4b", nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "424242", nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", "656565", "4c4c4c", },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", "4e4e4e", "434343", },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "161616", "181818", "171717", "181818", "181818", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "898989", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7e7e7e", },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7b7b7b", "646464", },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, "5b5b5b", "4e4e4e", },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "7d7d7d", },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "5a5a5a", },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "161616", "181818", "171717", "181818", "181818", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "4e4e4e", "8b8b8b", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "161616", "181818", "171717", "181818", "181818", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", "8b8b8b", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "8b8b8b", "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "4c4c4c", nil, "4c4c4c", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "4c4c4c", nil, nil, nil, "4c4c4c", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "8b8b8b", "4f4f4f", "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "4f4f4f", nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4f4f4f", nil, nil, nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "8b8b8b", "4f4f4f", "4f4f4f", "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, "8b8b8b", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4f4f4f", nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4f4f4f", nil, nil, nil, "4f4f4f", nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "181818", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "171717", "141414", "171717", "171717", "141414", "171717", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "171717", "151515", "171717", "141414", "161616", nil, nil, nil, "171717", "141414", "141414", "141414", "171717", "171717", "171717", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "171717", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "646464", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "171717", "151515", "151515", "171717", "171717", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "171717", "171717", "151515", "171717", "151515", "151515", nil, nil, nil, "171717", "171717", "151515", "151515", "151515", "161616", "171717", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "7c7c7c", "646464", "494949", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "5b5b5b", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "151515", "151515", "171717", "181818", "151515", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "151515", "151515", "181818", "151515", "171717", "151515", nil, nil, nil, "151515", "181818", "181818", "171717", "151515", "151515", "151515", },
        },
        {
            { nil, nil, nil, nil, nil, nil, nil, "2a2a2a", "2a2a2a", nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", "4e4e4e", "4e4e4e", "4e4e4e", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, nil, "8a8a8a", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "4e4e4e", nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "4e4e4e", nil, nil, nil, "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, nil, "7c7c7c", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "7c7c7c", "636363", "4e4e4e", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "585858", "4e4e4e", "434343", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
            { "151515", "171717", "151515", "151515", "171717", "171717", nil, nil, nil, "ffffff", nil, "ffffff", nil, "ffffff", nil, "ffffff", },
            { "171717", "171717", "151515", "171717", "151515", "151515", nil, nil, nil, "171717", "171717", "151515", "151515", "151515", "161616", "171717", },
        }
    }
}
